spring:
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dummy
    username: postgres
    password: admin

  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none