spring:
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dummy
    username: postgres
    password: admin

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  jackson:
    serialization:
      fail-on-empty-beans: false

  security:
    user:
      name: Gagan
      password: secret